/* Fragen-Fundus – generiert & geprüft. Notation: rac{}{} für Brüche, Rest Unicode. */
window.QUIZ = {
 "meta": {
  "titel": "Mathe Quiz-Turnier",
  "untertitel": "Klasse 6 · Jahresabschluss",
  "stand": "Juni 2026"
 },
 "bloecke": [
  {
   "id": "brueche",
   "name": "Brüche / Gebrochene Zahlen",
   "phase": "Anfang",
   "punkte": 30,
   "farbe": "#2E75B6"
  },
  {
   "id": "proportionalitaet",
   "name": "Proportionalität / Dreisatz",
   "phase": "Mitte",
   "punkte": 20,
   "farbe": "#70AD47"
  },
  {
   "id": "winkel",
   "name": "Winkel & Dreiecke",
   "phase": "Ende",
   "punkte": 10,
   "farbe": "#ED7D31"
  }
 ],
 "fragen": [
  {
   "id": "BR-001",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Berechne und kürze so weit wie möglich: \\frac{4}{7} \\cdot \\frac{2}{5}",
   "optionen": [
    "\\frac{8}{35}",
    "\\frac{6}{12}",
    "\\frac{8}{12}",
    "\\frac{6}{35}"
   ],
   "loesungIndex": 0,
   "loesung": "Bei der Multiplikation rechnet man Zähler mal Zähler und Nenner mal Nenner: 4·2=8 und 7·5=35, also \\frac{8}{35}. (Der Fehler \\frac{6}{12} entsteht durch Addieren statt Multiplizieren.)",
   "quelle": "Grundrechenarten mit Brüchen: 4/7·2/5",
   "niveau": "leicht"
  },
  {
   "id": "BR-002",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Berechne: \\frac{5}{6} : \\frac{5}{12}",
   "optionen": [
    "\\frac{25}{72}",
    "\\frac{1}{2}",
    "2",
    "\\frac{5}{8}"
   ],
   "loesungIndex": 2,
   "loesung": "Durch einen Bruch teilt man, indem man mit dem Kehrbruch multipliziert: \\frac{5}{6} \\cdot \\frac{12}{5} = \\frac{60}{30} = 2. (\\frac{25}{72} entsteht, wenn man fälschlich mit dem zweiten Bruch multipliziert statt mit dessen Kehrbruch.)",
   "quelle": "Grundrechenarten mit Brüchen: 5/6:5/12",
   "niveau": "mittel"
  },
  {
   "id": "BR-003",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Berechne: \\frac{4}{11} + \\frac{2}{7}",
   "optionen": [
    "\\frac{6}{18}",
    "\\frac{50}{77}",
    "\\frac{8}{77}",
    "\\frac{6}{77}"
   ],
   "loesungIndex": 1,
   "loesung": "Erst gleichnamig machen: \\frac{28}{77} + \\frac{22}{77} = \\frac{50}{77}. (\\frac{6}{18} entsteht durch falsches Addieren von Zählern und Nennern.)",
   "quelle": "Grundrechenarten mit Brüchen: 4/11+2/7",
   "niveau": "mittel"
  },
  {
   "id": "BR-004",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Berechne und kürze so weit wie möglich: \\frac{5}{7} − \\frac{3}{21}",
   "optionen": [
    "\\frac{2}{14}",
    "\\frac{2}{7}",
    "\\frac{4}{7}",
    "\\frac{2}{21}"
   ],
   "loesungIndex": 2,
   "loesung": "Gleichnamig machen: \\frac{5}{7} = \\frac{15}{21}, also \\frac{15}{21} − \\frac{3}{21} = \\frac{12}{21} = \\frac{4}{7}. (\\frac{2}{14} entsteht durch falsches Subtrahieren von Zählern und Nennern.)",
   "quelle": "Grundrechenarten mit Brüchen: 5/7−3/21",
   "niveau": "mittel"
  },
  {
   "id": "BR-005",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Berechne und kürze so weit wie möglich: \\frac{12}{35} \\cdot \\frac{7}{4}",
   "optionen": [
    "\\frac{3}{5}",
    "\\frac{21}{39}",
    "\\frac{19}{39}",
    "\\frac{5}{3}"
   ],
   "loesungIndex": 0,
   "loesung": "\\frac{12}{35} \\cdot \\frac{7}{4} = \\frac{84}{140}. Kürzen mit 28 ergibt \\frac{3}{5}. (Man kann auch vor dem Multiplizieren kürzen: 12 und 4 zu 3 und 1, 7 und 35 zu 1 und 5.)",
   "quelle": "Grundrechenarten mit Brüchen: 12/35·7/4",
   "niveau": "schwer"
  },
  {
   "id": "BR-006",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Berechne den mehrgliedrigen Term (Punkt vor Strich beachten): \\frac{1}{9} + \\frac{1}{3} : \\frac{3}{2}",
   "optionen": [
    "\\frac{1}{3}",
    "\\frac{4}{9}",
    "\\frac{2}{3}",
    "\\frac{1}{2}"
   ],
   "loesungIndex": 0,
   "loesung": "Zuerst die Division: \\frac{1}{3} : \\frac{3}{2} = \\frac{1}{3} \\cdot \\frac{2}{3} = \\frac{2}{9}. Dann \\frac{1}{9} + \\frac{2}{9} = \\frac{3}{9} = \\frac{1}{3}.",
   "quelle": "Mehrgliedrige Terme: 1/9+1/3:3/2",
   "niveau": "schwer"
  },
  {
   "id": "BR-007",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Berechne und kürze so weit wie möglich (Distributivgesetz oder gliedweise): \\frac{3}{4} \\cdot \\frac{7}{6} + \\frac{3}{4} \\cdot \\frac{5}{6}",
   "optionen": [
    "\\frac{3}{2}",
    "\\frac{4}{3}",
    "\\frac{1}{2}",
    "2"
   ],
   "loesungIndex": 0,
   "loesung": "\\frac{3}{4} \\cdot \\frac{7}{6} = \\frac{21}{24} und \\frac{3}{4} \\cdot \\frac{5}{6} = \\frac{15}{24}. Summe: \\frac{36}{24} = \\frac{3}{2}. (Schneller mit Distributivgesetz: \\frac{3}{4} \\cdot (\\frac{7}{6}+\\frac{5}{6}) = \\frac{3}{4} \\cdot 2 = \\frac{3}{2}.)",
   "quelle": "Mehrgliedrige Terme: 3/4·7/6+3/4·5/6",
   "niveau": "schwer"
  },
  {
   "id": "BR-008",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Berechne und kürze so weit wie möglich (Klammer zuerst): \\frac{5}{6} \\cdot \\left(\\frac{6}{5} + \\frac{2}{3}\\right)",
   "optionen": [
    "\\frac{14}{9}",
    "1",
    "\\frac{7}{9}",
    "\\frac{11}{8}"
   ],
   "loesungIndex": 0,
   "loesung": "Klammer: \\frac{6}{5} + \\frac{2}{3} = \\frac{18}{15} + \\frac{10}{15} = \\frac{28}{15}. Dann \\frac{5}{6} \\cdot \\frac{28}{15} = \\frac{140}{90} = \\frac{14}{9}. (Die Antwort 1 entsteht, wenn man nur \\frac{5}{6}·\\frac{6}{5} rechnet und den zweiten Summanden vergisst.)",
   "quelle": "Mehrgliedrige Terme: 5/6·(6/5+2/3)",
   "niveau": "schwer"
  },
  {
   "id": "BR-009",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Wandle die gemischte Zahl um und berechne: 2\\frac{2}{4} − \\frac{1}{5}",
   "optionen": [
    "\\frac{23}{10}",
    "2\\frac{1}{10}",
    "\\frac{13}{20}",
    "2\\frac{3}{20}"
   ],
   "loesungIndex": 0,
   "loesung": "2\\frac{2}{4} = 2\\frac{1}{2} = \\frac{5}{2} = \\frac{25}{10}. Dann \\frac{25}{10} − \\frac{2}{10} = \\frac{23}{10} (das sind 2\\frac{3}{10}).",
   "quelle": "Gemischte Zahlen: 2 2/4 − 1/5",
   "niveau": "mittel"
  },
  {
   "id": "BR-010",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Berechne und kürze so weit wie möglich den Doppelbruch: \\frac{\\frac{5}{7}}{\\frac{5}{3}}",
   "optionen": [
    "\\frac{3}{7}",
    "\\frac{25}{21}",
    "\\frac{7}{3}",
    "\\frac{5}{3}"
   ],
   "loesungIndex": 0,
   "loesung": "Ein Doppelbruch bedeutet Zähler geteilt durch Nenner: \\frac{5}{7} : \\frac{5}{3} = \\frac{5}{7} \\cdot \\frac{3}{5} = \\frac{15}{35} = \\frac{3}{7}. (\\frac{25}{21} entsteht, wenn man fälschlich mit \\frac{5}{3} statt mit dem Kehrbruch \\frac{3}{5} multipliziert.)",
   "quelle": "Doppelbrüche: (5/7)/(5/3)",
   "niveau": "schwer"
  },
  {
   "id": "BR-011",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Setze das richtige Zeichen ein: \\frac{2}{7} \\;\\square\\; \\frac{5}{14}",
   "optionen": [
    "<",
    ">",
    "=",
    "lässt sich nicht vergleichen"
   ],
   "loesungIndex": 0,
   "loesung": "Gleichnamig machen: \\frac{2}{7} = \\frac{4}{14}. Da \\frac{4}{14} < \\frac{5}{14} ist, gilt \\frac{2}{7} < \\frac{5}{14}.",
   "quelle": "Größenvergleich: 2/7 und 5/14",
   "niveau": "mittel"
  },
  {
   "id": "BR-012",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Welche gebrochene Zahl liegt auf dem Zahlenstrahl genau in der Mitte zwischen \\frac{1}{5} und \\frac{4}{10}?",
   "optionen": [
    "\\frac{3}{10}",
    "\\frac{5}{15}",
    "\\frac{1}{4}",
    "\\frac{4}{10}"
   ],
   "loesungIndex": 0,
   "loesung": "\\frac{1}{5} = \\frac{2}{10} und \\frac{4}{10}. Der Mittelwert ist (\\frac{2}{10} + \\frac{4}{10}) : 2 = \\frac{6}{10} : 2 = \\frac{3}{10}.",
   "quelle": "Zahlenstrahl: Bruch genau in der Mitte zweier Punkte",
   "niveau": "mittel"
  },
  {
   "id": "BR-013",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Sachaufgabe: Die ISS umrundet die Erde etwa in 1\\frac{1}{2} Stunden. Wie oft umrundet sie die Erde in 24 Stunden?",
   "optionen": [
    "16-mal",
    "36-mal",
    "12-mal",
    "24-mal"
   ],
   "loesungIndex": 0,
   "loesung": "Man teilt die Gesamtzeit durch die Umrundungsdauer: 24 : 1\\frac{1}{2} = 24 : \\frac{3}{2} = 24 \\cdot \\frac{2}{3} = 16. Also 16-mal. (36 entsteht, wenn man fälschlich mal \\frac{3}{2} rechnet.)",
   "quelle": "Sachaufgabe: ISS umrundet Erde in ca. 1 1/2 Stunden",
   "niveau": "schwer"
  },
  {
   "id": "BR-014",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "mc",
   "frage": "Sachaufgabe: Die Erdoberfläche ist zu \\frac{7}{10} mit Wasser bedeckt. Davon entfallen \\frac{6}{25} auf den zu Afrika gehörenden Wasseranteil. Welchen Anteil an der gesamten Erdoberfläche macht dieser Teil aus? Kürze so weit wie möglich.",
   "optionen": [
    "\\frac{21}{125}",
    "\\frac{13}{35}",
    "\\frac{31}{125}",
    "\\frac{6}{25}"
   ],
   "loesungIndex": 0,
   "loesung": "Anteil vom Anteil bedeutet multiplizieren: \\frac{7}{10} \\cdot \\frac{6}{25} = \\frac{42}{250} = \\frac{21}{125}. (\\frac{13}{35} entsteht durch falsches Addieren der Brüche.)",
   "quelle": "Sachaufgabe: Erdoberfläche 7/10 Wasser, davon 6/25 Afrika",
   "niveau": "schwer"
  },
  {
   "id": "BR-015",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Berechne und kürze so weit wie möglich: \\frac{4}{7} \\cdot \\frac{2}{5}",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Zähler mal Zähler, Nenner mal Nenner: \\frac{4}{7} \\cdot \\frac{2}{5} = \\frac{4 \\cdot 2}{7 \\cdot 5} = \\frac{8}{35}. Der Bruch \\frac{8}{35} lässt sich nicht weiter kürzen. Ergebnis: \\frac{8}{35}",
   "quelle": "Grundrechenarten mit Brüchen (Multiplikation)",
   "niveau": "leicht"
  },
  {
   "id": "BR-016",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Berechne: \\frac{4}{11} + \\frac{2}{7}",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Brüche auf den Hauptnenner 77 bringen: \\frac{4}{11} = \\frac{28}{77} und \\frac{2}{7} = \\frac{22}{77}. Dann addieren: \\frac{28}{77} + \\frac{22}{77} = \\frac{50}{77}. Der Bruch lässt sich nicht kürzen. Ergebnis: \\frac{50}{77}",
   "quelle": "Grundrechenarten mit Brüchen (Addition, ungleiche Nenner)",
   "niveau": "mittel"
  },
  {
   "id": "BR-017",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Berechne: \\frac{5}{6} : \\frac{5}{12}",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Durch einen Bruch teilt man, indem man mit dem Kehrbruch multipliziert: \\frac{5}{6} : \\frac{5}{12} = \\frac{5}{6} \\cdot \\frac{12}{5} = \\frac{5 \\cdot 12}{6 \\cdot 5} = \\frac{60}{30} = 2. Ergebnis: 2",
   "quelle": "Grundrechenarten mit Brüchen (Division)",
   "niveau": "mittel"
  },
  {
   "id": "BR-018",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Berechne mit Punkt-vor-Strich-Regel: \\frac{1}{9} + \\frac{1}{3} : \\frac{3}{2}",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Zuerst die Division (Punkt vor Strich): \\frac{1}{3} : \\frac{3}{2} = \\frac{1}{3} \\cdot \\frac{2}{3} = \\frac{2}{9}. Dann addieren: \\frac{1}{9} + \\frac{2}{9} = \\frac{3}{9} = \\frac{1}{3}. Ergebnis: \\frac{1}{3}",
   "quelle": "Mehrgliedrige Terme (Punkt vor Strich)",
   "niveau": "schwer"
  },
  {
   "id": "BR-019",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Berechne und gib das Ergebnis als gemischte Zahl an: 2\\frac{2}{4} - \\frac{1}{5}",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Zuerst 2\\frac{2}{4} kürzen zu 2\\frac{1}{2}. Auf den gemeinsamen Nenner 10 bringen: 2\\frac{1}{2} = 2\\frac{5}{10} und \\frac{1}{5} = \\frac{2}{10}. Subtrahieren: 2\\frac{5}{10} - \\frac{2}{10} = 2\\frac{3}{10}. Ergebnis: 2\\frac{3}{10}",
   "quelle": "Gemischte Zahlen (Subtraktion)",
   "niveau": "mittel"
  },
  {
   "id": "BR-020",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Berechne geschickt durch Ausklammern: \\frac{3}{4} \\cdot \\frac{7}{6} + \\frac{3}{4} \\cdot \\frac{5}{6}",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Der Faktor \\frac{3}{4} kommt zweimal vor, also ausklammern: \\frac{3}{4} \\cdot \\left(\\frac{7}{6} + \\frac{5}{6}\\right) = \\frac{3}{4} \\cdot \\frac{12}{6} = \\frac{3}{4} \\cdot 2 = \\frac{6}{4} = \\frac{3}{2} = 1\\frac{1}{2}. Ergebnis: 1\\frac{1}{2}",
   "quelle": "Mehrgliedrige Terme (Distributivgesetz)",
   "niveau": "schwer"
  },
  {
   "id": "BR-021",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Berechne den Doppelbruch und kürze: \\frac{\\frac{4}{5} - \\frac{3}{10}}{\\frac{2}{9} : \\frac{1}{3}}",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Zähler ausrechnen: \\frac{4}{5} - \\frac{3}{10} = \\frac{8}{10} - \\frac{3}{10} = \\frac{5}{10} = \\frac{1}{2}. Nenner ausrechnen: \\frac{2}{9} : \\frac{1}{3} = \\frac{2}{9} \\cdot \\frac{3}{1} = \\frac{6}{9} = \\frac{2}{3}. Der Doppelbruch bedeutet Zähler geteilt durch Nenner: \\frac{1}{2} : \\frac{2}{3} = \\frac{1}{2} \\cdot \\frac{3}{2} = \\frac{3}{4}. Ergebnis: \\frac{3}{4}",
   "quelle": "Doppelbrüche",
   "niveau": "schwer"
  },
  {
   "id": "BR-022",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Setze das richtige Zeichen (< , > oder =) zwischen die beiden Zahlen und begründe: \\frac{2}{7} und \\frac{5}{14}",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Beide Brüche auf den gemeinsamen Nenner 14 bringen: \\frac{2}{7} = \\frac{4}{14}. Jetzt vergleichen: \\frac{4}{14} und \\frac{5}{14}. Bei gleichem Nenner ist der Bruch mit dem größeren Zähler größer, also \\frac{4}{14} < \\frac{5}{14}. Ergebnis: \\frac{2}{7} < \\frac{5}{14}",
   "quelle": "Größenvergleich mit Brüchen",
   "niveau": "leicht"
  },
  {
   "id": "BR-023",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Setze das richtige Zeichen (< , > oder =) und begründe: \\frac{5}{10} und 0,343",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Den Bruch in eine Dezimalzahl umwandeln: \\frac{5}{10} = 0,5. Jetzt zwei Dezimalzahlen vergleichen: 0,5 = 0,500 und 0,343. An der Zehntelstelle steht bei 0,500 eine 5, bei 0,343 eine 3, also ist 0,500 größer. Ergebnis: \\frac{5}{10} > 0,343",
   "quelle": "Größenvergleich Bruch und Dezimalzahl",
   "niveau": "mittel"
  },
  {
   "id": "BR-024",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Ordne die folgenden Zahlen der Größe nach (von der kleinsten zur größten), so wie sie auf dem Zahlenstrahl liegen: \\frac{1}{5} ; \\frac{4}{10} ; 0,8 ; 1\\frac{3}{10} ; \\frac{4}{20} ; 2,1",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Alle Zahlen als Dezimalzahl schreiben: \\frac{1}{5} = 0,2; \\frac{4}{10} = 0,4; 0,8 = 0,8; 1\\frac{3}{10} = 1,3; \\frac{4}{20} = \\frac{1}{5} = 0,2; 2,1 = 2,1. Der Größe nach geordnet: 0,2 = 0,2 < 0,4 < 0,8 < 1,3 < 2,1. Reihenfolge: \\frac{1}{5} = \\frac{4}{20} < \\frac{4}{10} < 0,8 < 1\\frac{3}{10} < 2,1. (Hinweis: \\frac{1}{5} und \\frac{4}{20} liegen an derselben Stelle.)",
   "quelle": "Zahlenstrahl (Brüche und Dezimalzahlen einordnen)",
   "niveau": "mittel"
  },
  {
   "id": "BR-025",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Nina surft pro Woche 4-mal eine halbe Stunde im Internet. Mathias surft pro Woche 7-mal eine Viertelstunde. Wer surft pro Woche länger und um wie viele Minuten?",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Ninas Zeit: 4 \\cdot \\frac{1}{2} h = \\frac{4}{2} h = 2 h, das sind 120 Minuten. Mathias' Zeit: 7 \\cdot \\frac{1}{4} h = \\frac{7}{4} h = 1\\frac{3}{4} h, das sind 105 Minuten. Vergleich: 120 min > 105 min. Nina surft länger, und zwar um 120 - 105 = 15 Minuten. Ergebnis: Nina surft 15 Minuten länger.",
   "quelle": "Sachaufgabe (Bruchteile von Größen)",
   "niveau": "mittel"
  },
  {
   "id": "BR-026",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Die Internationale Raumstation ISS umrundet die Erde in etwa 1\\frac{1}{2} Stunden einmal. Wie oft umrundet sie die Erde in 24 Stunden?",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Man teilt die Gesamtzeit durch die Zeit für eine Umrundung: 24 : 1\\frac{1}{2} = 24 : \\frac{3}{2} = 24 \\cdot \\frac{2}{3} = \\frac{48}{3} = 16. Die ISS umrundet die Erde in 24 Stunden also 16-mal. Ergebnis: 16 Umrundungen.",
   "quelle": "Sachaufgabe (Division mit gemischter Zahl)",
   "niveau": "schwer"
  },
  {
   "id": "BR-027",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "offen",
   "frage": "Die Erdoberfläche ist zu \\frac{7}{10} mit Wasser bedeckt. Von dieser Wasserfläche entfallen \\frac{6}{25} auf das Meer rund um Afrika. Welcher Anteil der gesamten Erdoberfläche ist das? Kürze das Ergebnis.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Man berechnet einen Bruchteil vom Bruchteil durch Multiplizieren: \\frac{6}{25} \\cdot \\frac{7}{10} = \\frac{6 \\cdot 7}{25 \\cdot 10} = \\frac{42}{250}. Jetzt kürzen mit 2: \\frac{42}{250} = \\frac{21}{125}. Ergebnis: \\frac{21}{125} der gesamten Erdoberfläche.",
   "quelle": "Sachaufgabe (Anteil vom Anteil, Multiplikation)",
   "niveau": "schwer"
  },
  {
   "id": "BR-028",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler in eigenen Worten, wie man zwei Brueche miteinander multipliziert. Erklaere es am Beispiel \\frac{4}{7} \\cdot \\frac{2}{5}.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: (1) Bei der Multiplikation von Bruechen rechnet man 'Zaehler mal Zaehler' und 'Nenner mal Nenner' — man muss NICHT auf gleichen Nenner bringen. (2) Beim Beispiel: Zaehler 4 \\cdot 2 = 8, Nenner 7 \\cdot 5 = 35. (3) Ergebnis: \\frac{8}{35}. (4) Pruefen, ob man kuerzen kann — hier nicht, weil 8 und 35 keinen gemeinsamen Teiler haben.",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "leicht"
  },
  {
   "id": "BR-029",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Ein Mitschueler weiss nicht, wie man zwei Brueche mit verschiedenen Nennern addiert. Erklaere ihm das Vorgehen am Beispiel \\frac{4}{11} + \\frac{2}{7}.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) Man kann Brueche nur addieren, wenn sie den gleichen Nenner (Hauptnenner) haben. (2) Hauptnenner finden: 11 \\cdot 7 = 77. (3) Beide Brueche erweitern: \\frac{4}{11} = \\frac{28}{77} (mal 7), \\frac{2}{7} = \\frac{22}{77} (mal 11). (4) Jetzt nur die Zaehler addieren, der Nenner bleibt gleich: \\frac{28}{77} + \\frac{22}{77} = \\frac{50}{77}. (5) Wichtig: Nenner werden NICHT addiert. Ergebnis \\frac{50}{77} laesst sich nicht kuerzen.",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "mittel"
  },
  {
   "id": "BR-030",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, wie man durch einen Bruch teilt. Nutze das Beispiel \\frac{5}{6} : \\frac{5}{12} und erklaere die Regel 'mit dem Kehrwert multiplizieren'.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) Durch einen Bruch teilen bedeutet: mit seinem Kehrwert multiplizieren. (2) Der Kehrwert entsteht, indem man Zaehler und Nenner vertauscht — aus \\frac{5}{12} wird \\frac{12}{5}. (3) Also: \\frac{5}{6} : \\frac{5}{12} = \\frac{5}{6} \\cdot \\frac{12}{5}. (4) Man darf vorher kuerzen: die 5 oben und unten weg, 6 und 12 ergeben 1 zu 2. So bleibt \\frac{1}{1} \\cdot \\frac{2}{1} = 2. (5) Ergebnis: 2. Hinweis: Beim Teilen wird nur der zweite Bruch (der Teiler) gekehrt, nicht der erste.",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "mittel"
  },
  {
   "id": "BR-031",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Dein Mitschueler rechnet \\frac{3}{4} \\cdot \\frac{4}{3} und ist ueberrascht, dass 1 herauskommt. Erklaere ihm, warum das Ergebnis genau 1 ist und was die beiden Brueche miteinander zu tun haben.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) \\frac{4}{3} ist der Kehrwert von \\frac{3}{4} (Zaehler und Nenner sind vertauscht). (2) Multipliziert man einen Bruch mit seinem Kehrwert, kommt immer 1 heraus. (3) Nachrechnen: Zaehler 3 \\cdot 4 = 12, Nenner 4 \\cdot 3 = 12, also \\frac{12}{12} = 1. (4) Anschaulich: Wenn Zaehler und Nenner gleich sind, ist der Bruch ein Ganzes, also 1.",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "leicht"
  },
  {
   "id": "BR-032",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, was 'Kuerzen' bei einem Bruch bedeutet und warum sich der Wert des Bruchs dabei nicht aendert. Zeige es am Beispiel \\frac{5}{7} − \\frac{3}{21}.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) Kuerzen heisst: Zaehler und Nenner durch dieselbe Zahl teilen. (2) Der Wert aendert sich nicht, weil man im Grunde durch 1 teilt (z. B. \\frac{3}{3}) — man schreibt denselben Anteil nur mit kleineren Zahlen. (3) Beim Beispiel sieht man, dass \\frac{3}{21} sich durch 3 kuerzen laesst: \\frac{3}{21} = \\frac{1}{7}. (4) Jetzt haben beide Brueche denselben Nenner: \\frac{5}{7} − \\frac{1}{7} = \\frac{4}{7}. (5) Ergebnis: \\frac{4}{7}. Kuerzen macht das Rechnen einfacher, weil man oft gleich passende Nenner bekommt.",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "mittel"
  },
  {
   "id": "BR-033",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, was eine 'gemischte Zahl' ist und wie man sie in einen unechten Bruch umwandelt. Wandle dabei 2 \\frac{2}{4} um und vereinfache zuerst.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) Eine gemischte Zahl besteht aus einem ganzen Teil und einem Bruchteil, z. B. 2 \\frac{2}{4} heisst '2 Ganze und \\frac{2}{4}'. (2) Erst kuerzen: \\frac{2}{4} = \\frac{1}{2}, also 2 \\frac{1}{2}. (3) Umwandeln in unechten Bruch: ganze Zahl mal Nenner plus Zaehler, das Ganze ueber den Nenner: 2 \\cdot 2 + 1 = 5, also \\frac{5}{2}. (4) Kontrolle: \\frac{5}{2} = 2,5 = 2 \\frac{1}{2}. Ein unechter Bruch hat einen Zaehler, der groesser (oder gleich) dem Nenner ist.",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "mittel"
  },
  {
   "id": "BR-034",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Bei der Aufgabe \\frac{1}{9} + \\frac{1}{3} : \\frac{3}{2} weiss dein Mitschueler nicht, was er zuerst rechnen muss. Erklaere ihm die Rechenreihenfolge und loese die Aufgabe gemeinsam.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) Es gilt 'Punkt vor Strich': Mal- und Geteilt-Rechnung kommen vor Plus und Minus. (2) Also zuerst \\frac{1}{3} : \\frac{3}{2} rechnen — Teilen heisst mit dem Kehrwert mal: \\frac{1}{3} \\cdot \\frac{2}{3} = \\frac{2}{9}. (3) Dann erst die Addition: \\frac{1}{9} + \\frac{2}{9} = \\frac{3}{9}. (4) Kuerzen: \\frac{3}{9} = \\frac{1}{3}. (5) Ergebnis: \\frac{1}{3}. Wer hier von links nach rechts rechnet, bekommt ein falsches Ergebnis — deshalb ist die Reihenfolge so wichtig.",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "schwer"
  },
  {
   "id": "BR-035",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, was ein 'Doppelbruch' ist und wie man ihn vereinfacht. Nutze das Beispiel \\frac{5/7}{5/3} (also \\frac{5}{7} geteilt durch \\frac{5}{3}).",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) Ein Doppelbruch ist ein Bruch, bei dem im Zaehler und/oder im Nenner selbst wieder ein Bruch steht. (2) Der grosse Bruchstrich bedeutet 'geteilt durch': oberer Bruch geteilt durch unteren Bruch. (3) Also \\frac{5}{7} : \\frac{5}{3} = \\frac{5}{7} \\cdot \\frac{3}{5} (mit dem Kehrwert mal). (4) Die 5 oben und unten kuerzen sich weg: es bleibt \\frac{3}{7}. (5) Ergebnis: \\frac{3}{7}. Merksatz: 'Der Hauptbruchstrich ist ein Geteilt-Zeichen.'",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "schwer"
  },
  {
   "id": "BR-036",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, wie man den Bruch \\frac{4}{10} und die Dezimalzahl 0,8 auf einem Zahlenstrahl von 0 bis 1 richtig einordnet und welche der beiden Zahlen weiter rechts liegt.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) Zwischen 0 und 1 teilt man den Strahl in gleich grosse Abschnitte; bei Zehnteln in 10 Teile. (2) \\frac{4}{10} bedeutet 4 von 10 Teilen, also der 4. Strich nach 0; das ist dasselbe wie 0,4. (3) 0,8 ist der 8. Strich, also \\frac{8}{10}. (4) Vergleich: 0,8 liegt weiter rechts (ist groesser) als \\frac{4}{10} = 0,4. (5) Wichtig: Wer rechts liegt, ist die groessere Zahl. \\frac{4}{10} < 0,8.",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "leicht"
  },
  {
   "id": "BR-037",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, wie man herausfindet, ob \\frac{2}{7} oder \\frac{5}{14} groesser ist, ohne zu raten. Schreibe das Vergleichszeichen <, > oder = hin.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) Brueche kann man nur direkt vergleichen, wenn sie denselben Nenner haben. (2) \\frac{2}{7} auf den Nenner 14 erweitern (mal 2): \\frac{2}{7} = \\frac{4}{14}. (3) Jetzt beide mit Nenner 14 vergleichen: \\frac{4}{14} und \\frac{5}{14} — bei gleichem Nenner ist der mit dem groesseren Zaehler groesser. (4) Also \\frac{4}{14} < \\frac{5}{14}, das heisst \\frac{2}{7} < \\frac{5}{14}. (5) Ergebnis: \\frac{2}{7} < \\frac{5}{14}.",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "mittel"
  },
  {
   "id": "BR-038",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, wie man die Sachaufgabe loest: Nina surft 4-mal pro Woche je eine halbe Stunde, Mathias 7-mal pro Woche je eine Viertelstunde. Wer surft pro Woche laenger? Erklaere deinen Rechenweg.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) 'Eine halbe Stunde' ist \\frac{1}{2} Stunde, 'eine Viertelstunde' ist \\frac{1}{4} Stunde. (2) Nina gesamt: 4 \\cdot \\frac{1}{2} = \\frac{4}{2} = 2 Stunden. (3) Mathias gesamt: 7 \\cdot \\frac{1}{4} = \\frac{7}{4} = 1 \\frac{3}{4} Stunden. (4) Vergleich: 2 Stunden gegen 1 \\frac{3}{4} Stunden — 2 ist groesser. (5) Ergebnis: Nina surft laenger (2 h gegenueber 1 \\frac{3}{4} h, also 15 Minuten mehr).",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "mittel"
  },
  {
   "id": "BR-039",
   "block": "brueche",
   "phase": "Anfang",
   "punkte": 30,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, wie man die Sachaufgabe loest: Die Erdoberflaeche ist zu \\frac{7}{10} mit Wasser bedeckt, und davon entfallen \\frac{6}{25} auf den Bereich um Afrika. Welchen Anteil an der GESAMTEN Erdoberflaeche macht dieser Teil aus? Erklaere, warum man hier multipliziert.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte: (1) Das Wort 'davon' bedeutet 'ein Anteil von einem Anteil' — und 'Anteil von Anteil' rechnet man mit Mal (Multiplikation). (2) Gesucht: \\frac{6}{25} von \\frac{7}{10}, also \\frac{6}{25} \\cdot \\frac{7}{10}. (3) Zaehler mal Zaehler: 6 \\cdot 7 = 42; Nenner mal Nenner: 25 \\cdot 10 = 250. Also \\frac{42}{250}. (4) Kuerzen durch 2: \\frac{42}{250} = \\frac{21}{125}. (5) Ergebnis: \\frac{21}{125} der gesamten Erdoberflaeche. Merksatz: 'von' heisst mal.",
   "quelle": "Brueche / Gebrochene Zahlen",
   "niveau": "schwer"
  },
  {
   "id": "PR-001",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "Welche der folgenden Zuordnungen ist DIREKT proportional?",
   "optionen": [
    "Anzahl der Kinotickets → Gesamtpreis",
    "Größe der Fliesen → Anzahl der benötigten Fliesen",
    "Anzahl der Maschinen → Arbeitsdauer",
    "Länge eines Kinofilms → Anzahl der Zuschauer"
   ],
   "loesungIndex": 0,
   "loesung": "Je mehr Tickets, desto mehr kostet es im selben Verhältnis (doppelt so viele Tickets = doppelter Preis). Das ist direkt proportional. Die anderen sind indirekt (Fliesen, Maschinen) bzw. gar nicht proportional (Filmlänge).",
   "quelle": "direkt vs. indirekt proportional erkennen",
   "niveau": "leicht"
  },
  {
   "id": "PR-002",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "Welche der folgenden Zuordnungen ist INDIREKT (umgekehrt) proportional?",
   "optionen": [
    "Benzinmenge → Gesamtkosten",
    "Arbeitszeit → Lohn",
    "Anzahl der Maschinen → Arbeitsdauer",
    "Länge des Schulwegs → Anzahl der Schritte"
   ],
   "loesungIndex": 2,
   "loesung": "Je mehr Maschinen arbeiten, desto kürzer dauert die Arbeit (doppelt so viele Maschinen = halbe Zeit). Das ist indirekt proportional. Die anderen drei sind direkt proportional.",
   "quelle": "direkt vs. indirekt proportional erkennen",
   "niveau": "leicht"
  },
  {
   "id": "PR-003",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "Welche Zuordnung ist WEDER direkt NOCH indirekt proportional?",
   "optionen": [
    "Länge eines Kinofilms → Anzahl der Zuschauer",
    "Anzahl der Kinotickets → Gesamtpreis",
    "Benzinmenge → Gesamtkosten",
    "Zahl x → ein Drittel von x"
   ],
   "loesungIndex": 0,
   "loesung": "Ob ein Film länger ist, sagt nichts darüber aus, wie viele Zuschauer kommen. Diese Zuordnung ist nicht proportional. Die anderen drei sind direkt proportional.",
   "quelle": "direkt vs. indirekt proportional erkennen",
   "niveau": "mittel"
  },
  {
   "id": "PR-004",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "Eine Wertetabelle ist direkt proportional. Bei x = 5 steht y = 20. Welcher y-Wert gehört zu x = 50?",
   "optionen": [
    "65",
    "200",
    "100",
    "500"
   ],
   "loesungIndex": 1,
   "loesung": "Der Quotient k = y : x ist konstant: 20 : 5 = 4. Also y = 50 \\cdot 4 = 200.",
   "quelle": "Wertetabelle direkt proportional, k=4",
   "niveau": "mittel"
  },
  {
   "id": "PR-005",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "Eine Wertetabelle ist indirekt proportional mit dem Produkt x \\cdot y = 60. Welcher y-Wert gehört zu x = 12?",
   "optionen": [
    "48",
    "72",
    "5",
    "15"
   ],
   "loesungIndex": 2,
   "loesung": "Bei indirekter Proportionalität ist das Produkt x \\cdot y konstant (hier 60). Also y = 60 : 12 = 5.",
   "quelle": "Wertetabelle indirekt proportional, k=60",
   "niveau": "mittel"
  },
  {
   "id": "PR-006",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "9 Eintrittskarten kosten 81 €. Was kosten 11 Karten (gleicher Preis pro Karte)?",
   "optionen": [
    "90 €",
    "99 €",
    "108 €",
    "891 €"
   ],
   "loesungIndex": 1,
   "loesung": "Eine Karte kostet 81 € : 9 = 9 €. 11 Karten kosten 11 \\cdot 9 € = 99 €. (Direkter Dreisatz.)",
   "quelle": "Dreisatz: 9 Karten 81 € → 11 Karten 99 €",
   "niveau": "mittel"
  },
  {
   "id": "PR-007",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "2 gleiche Pumpen leeren ein Becken in 4 Stunden. Wie lange brauchen 5 Pumpen?",
   "optionen": [
    "1,6 Stunden",
    "10 Stunden",
    "2 Stunden",
    "0,8 Stunden"
   ],
   "loesungIndex": 0,
   "loesung": "Indirekter Dreisatz: 1 Pumpe braucht 2 \\cdot 4 h = 8 h. 5 Pumpen brauchen 8 h : 5 = 1,6 h.",
   "quelle": "Dreisatz indirekt: 2 Pumpen 4 h → 5 Pumpen 1,6 h",
   "niveau": "schwer"
  },
  {
   "id": "PR-008",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "5 kg Tomaten kosten 13 €. Was kosten 2,5 kg?",
   "optionen": [
    "6,50 €",
    "26 €",
    "5,20 €",
    "2,60 €"
   ],
   "loesungIndex": 0,
   "loesung": "2,5 kg ist die Hälfte von 5 kg, also ist auch der Preis die Hälfte: 13 € : 2 = 6,50 €. (1 kg kostet 13 € : 5 = 2,60 €; 2,5 \\cdot 2,60 € = 6,50 €.)",
   "quelle": "Dreisatz: 5 kg Tomaten 13 € → 2,5 kg",
   "niveau": "mittel"
  },
  {
   "id": "PR-009",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "Zum Wertepaar (6 | 9) gehört eine direkt proportionale Zuordnung. Wie groß ist der Proportionalitätsfaktor k?",
   "optionen": [
    "1,5",
    "3",
    "0,75",
    "54"
   ],
   "loesungIndex": 0,
   "loesung": "Der Proportionalitätsfaktor ist k = y : x = 9 : 6 = 1,5.",
   "quelle": "Proportionalitätsfaktor aus Wertepaar (6|9) → k=1,5",
   "niveau": "mittel"
  },
  {
   "id": "PR-010",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "Wie sieht der Graph einer direkt proportionalen Zuordnung aus?",
   "optionen": [
    "Eine Halbgerade, die durch den Ursprung (0|0) geht",
    "Eine Gerade, die die y-Achse oberhalb des Ursprungs schneidet",
    "Eine gekrümmte Kurve (Hyperbel)",
    "Eine waagerechte Linie"
   ],
   "loesungIndex": 0,
   "loesung": "Eine direkt proportionale Zuordnung wird durch eine Halbgerade dargestellt, die im Ursprung (0|0) beginnt, denn zu x = 0 gehört immer y = 0. Die Hyperbel gehört zur indirekten Proportionalität.",
   "quelle": "Graph direkt proportional: Halbgerade durch Ursprung",
   "niveau": "leicht"
  },
  {
   "id": "PR-011",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "Ein Brötchen kostet 0,24 €. Was kosten 7 Brötchen?",
   "optionen": [
    "1,68 €",
    "1,44 €",
    "0,31 €",
    "2,40 €"
   ],
   "loesungIndex": 0,
   "loesung": "Direkter Dreisatz: 7 \\cdot 0,24 € = 1,68 €.",
   "quelle": "Wertetabelle Brötchen: 1 Stück 0,24 €",
   "niveau": "leicht"
  },
  {
   "id": "PR-012",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "mc",
   "frage": "In einer indirekt proportionalen Wertetabelle gilt x \\cdot y = 60. Zu x = 4 gehört y = 15. Welcher y-Wert gehört zu x = 10?",
   "optionen": [
    "6",
    "21",
    "600",
    "37,5"
   ],
   "loesungIndex": 0,
   "loesung": "Das Produkt bleibt konstant 60. Also y = 60 : 10 = 6.",
   "quelle": "Wertetabelle indirekt proportional, k=60",
   "niveau": "mittel"
  },
  {
   "id": "PR-013",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "Entscheide bei jeder Zuordnung, ob sie direkt proportional, indirekt (umgekehrt) proportional oder weder noch ist. Begruende jeweils kurz.\na) Anzahl der Kinotickets → Gesamtpreis\nb) Groesse der Fliesen → Anzahl der benoetigten Fliesen fuer einen Boden\nc) Laenge eines Kinofilms → Anzahl der Zuschauer",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "a) direkt proportional: Je mehr Tickets, desto teurer; doppelt so viele Tickets kosten doppelt so viel. Der Quotient Preis : Anzahl (Preis pro Ticket) bleibt gleich.\nb) indirekt (umgekehrt) proportional: Je groesser eine Fliese ist, desto weniger Fliesen braucht man. Doppelt so grosse Fliesen → halb so viele Fliesen; das Produkt aus Fliesengroesse und Anzahl bleibt gleich.\nc) weder noch (nicht proportional): Die Laenge eines Films hat keinen festen rechnerischen Zusammenhang mit der Zuschauerzahl. Ein langer Film kann wenige oder viele Zuschauer haben.",
   "quelle": "Proportionalitaet: direkt vs. indirekt erkennen",
   "niveau": "leicht"
  },
  {
   "id": "PR-014",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "Ordne jede Zuordnung richtig ein (direkt proportional / indirekt proportional). Begruende mit einem Satz.\na) Anzahl der Maschinen, die gleich schnell arbeiten → Arbeitsdauer fuer einen festen Auftrag\nb) getankte Benzinmenge → Gesamtkosten an der Tankstelle\nc) Arbeitszeit → Lohn (bei festem Stundenlohn)",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "a) indirekt proportional: Mehr Maschinen erledigen die feste Arbeit in kuerzerer Zeit. Doppelt so viele Maschinen → halbe Dauer; Maschinenzahl · Dauer bleibt konstant.\nb) direkt proportional: Doppelt so viel Benzin kostet doppelt so viel. Der Preis pro Liter (Kosten : Menge) ist konstant.\nc) direkt proportional: Doppelt so lange Arbeitszeit ergibt doppelt so viel Lohn. Der Stundenlohn (Lohn : Zeit) bleibt gleich.",
   "quelle": "Proportionalitaet: direkt vs. indirekt erkennen",
   "niveau": "leicht"
  },
  {
   "id": "PR-015",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "Die folgende Wertetabelle gehoert zu einer direkt proportionalen Zuordnung. Ergaenze die fehlenden Werte und gib den Proportionalitaetsfaktor k an.\nx: 1 ; 2,5 ; 5 ; ___ ; 50\ny: 4 ; 10 ; ___ ; 40 ; 200",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Bei direkter Proportionalitaet ist der Quotient k = y : x konstant. Aus dem Paar (1 | 4): k = 4 : 1 = 4.\nFehlendes y bei x = 5: y = 5 · 4 = 20.\nFehlendes x bei y = 40: x = 40 : 4 = 10.\nVollstaendige Tabelle: x: 1 ; 2,5 ; 5 ; 10 ; 50  und  y: 4 ; 10 ; 20 ; 40 ; 200.\nProbe: 10 : 2,5 = 4, 200 : 50 = 4. Proportionalitaetsfaktor k = 4.",
   "quelle": "Wertetabelle direkt proportional ergaenzen (k=4)",
   "niveau": "leicht"
  },
  {
   "id": "PR-016",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "Die Wertetabelle gehoert zu einer indirekt (umgekehrt) proportionalen Zuordnung. Ergaenze die fehlenden Werte und gib den konstanten Wert k an.\nx: 2 ; 4 ; 10 ; 12 ; ___\ny: 30 ; ___ ; 6 ; 5 ; 3",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Bei indirekter Proportionalitaet ist das Produkt k = x · y konstant. Aus dem Paar (2 | 30): k = 2 · 30 = 60.\nFehlendes y bei x = 4: y = 60 : 4 = 15.\nFehlendes x bei y = 3: x = 60 : 3 = 20.\nVollstaendige Tabelle: x: 2 ; 4 ; 10 ; 12 ; 20  und  y: 30 ; 15 ; 6 ; 5 ; 3.\nProbe: 10 · 6 = 60, 12 · 5 = 60. Konstante k = 60.",
   "quelle": "Wertetabelle indirekt proportional ergaenzen (k=60)",
   "niveau": "mittel"
  },
  {
   "id": "PR-017",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "9 gleiche Eintrittskarten kosten zusammen 81 €. Wie viel kosten 11 dieser Karten? Rechne mit dem Dreisatz und schreibe alle drei Schritte auf.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Direkt proportional: mehr Karten → mehr Geld.\nSchritt 1 (gegeben): 9 Karten kosten 81 €.\nSchritt 2 (auf 1 Karte): 1 Karte kostet 81 € : 9 = 9 €.\nSchritt 3 (auf 11 Karten): 11 Karten kosten 9 € · 11 = 99 €.\nErgebnis: 11 Karten kosten 99 €.",
   "quelle": "Dreisatz direkt: 9 Karten 81 € → 11 Karten",
   "niveau": "leicht"
  },
  {
   "id": "PR-018",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "2 gleich starke Pumpen leeren ein Regenwasserbecken in 4 Stunden. Wie lange brauchen 5 dieser Pumpen fuer dasselbe Becken? Begruende zuerst, ob direkt oder indirekt proportional, und rechne dann mit dem Dreisatz.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Indirekt (umgekehrt) proportional: mehr Pumpen → kuerzere Zeit.\nSchritt 1 (gegeben): 2 Pumpen brauchen 4 h.\nSchritt 2 (auf 1 Pumpe): 1 Pumpe braucht 2 · 4 h = 8 h (eine Pumpe allein braucht laenger).\nSchritt 3 (auf 5 Pumpen): 5 Pumpen brauchen 8 h : 5 = 1,6 h.\nErgebnis: 5 Pumpen leeren das Becken in 1,6 Stunden (= 1 h 36 min). Probe: 2 · 4 = 8 und 5 · 1,6 = 8.",
   "quelle": "Dreisatz indirekt: 2 Pumpen 4 h → 5 Pumpen",
   "niveau": "mittel"
  },
  {
   "id": "PR-019",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "5 kg Tomaten kosten 13 €. Berechne mit dem Dreisatz\na) den Preis fuer 1 kg Tomaten und\nb) den Preis fuer 2,5 kg Tomaten.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Direkt proportional: mehr Tomaten → mehr Geld.\na) 1 kg: 13 € : 5 = 2,60 €.\nb) 2,5 kg: 2,60 € · 2,5 = 6,50 €.\nErgebnis: 1 kg kostet 2,60 €, 2,5 kg kosten 6,50 €.",
   "quelle": "Dreisatz direkt: Tomaten 5 kg 13 €",
   "niveau": "leicht"
  },
  {
   "id": "PR-020",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "Zu einer direkt proportionalen Zuordnung gehoert das Wertepaar (6 | 9). Berechne den Proportionalitaetsfaktor k und gib an, welcher y-Wert zu x = 10 gehoert.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Der Proportionalitaetsfaktor ist k = y : x = 9 : 6 = 1,5.\nDie Zuordnungsvorschrift lautet y = 1,5 · x.\nFuer x = 10: y = 1,5 · 10 = 15.\nErgebnis: k = 1,5 und zu x = 10 gehoert y = 15.",
   "quelle": "Proportionalitaetsfaktor aus Wertepaar (6|9) → k=1,5",
   "niveau": "mittel"
  },
  {
   "id": "PR-021",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "Ein Broetchen kostet 0,24 €. Erstelle eine Wertetabelle (Anzahl → Preis) fuer 5, 7, 10 und 12 Broetchen und begruende, warum es sich um eine direkt proportionale Zuordnung handelt.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Preis = Anzahl · 0,24 €.\n5 Broetchen: 5 · 0,24 € = 1,20 €.\n7 Broetchen: 7 · 0,24 € = 1,68 €.\n10 Broetchen: 10 · 0,24 € = 2,40 €.\n12 Broetchen: 12 · 0,24 € = 2,88 €.\nTabelle:  Anzahl: 5 ; 7 ; 10 ; 12  |  Preis in €: 1,20 ; 1,68 ; 2,40 ; 2,88.\nEs ist direkt proportional, weil der Quotient Preis : Anzahl immer 0,24 € (Preis pro Broetchen) ergibt; doppelt so viele Broetchen kosten doppelt so viel.",
   "quelle": "Wertetabelle Broetchen: 1 Stueck 0,24 €",
   "niveau": "leicht"
  },
  {
   "id": "PR-022",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "Die Zuordnung 'Zahl x → ein Drittel von x' soll untersucht werden.\na) Ist sie direkt proportional, indirekt proportional oder weder noch? Begruende.\nb) Berechne den Wert, der zu x = 21 gehoert, und gib den Proportionalitaetsfaktor k an.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "a) Direkt proportional: Es gilt y = \\frac{1}{3} \\cdot x. Der Quotient y : x = \\frac{1}{3} ist fuer jedes x gleich; verdoppelt man x, verdoppelt sich auch y.\nb) Zu x = 21 gehoert y = 21 : 3 = 7. Der Proportionalitaetsfaktor ist k = \\frac{1}{3}.",
   "quelle": "Proportionalitaet: Zahl x → ein Drittel von x (direkt)",
   "niveau": "mittel"
  },
  {
   "id": "PR-023",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "Lisas Schulweg ist 1200 m lang; dafuer braucht sie 1500 Schritte. Die Zuordnung 'Laenge des Schulwegs → Anzahl der Schritte' ist direkt proportional. Wie viele Schritte macht sie auf einem 2000 m langen Weg? Rechne mit dem Dreisatz.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Direkt proportional: laengerer Weg → mehr Schritte.\nSchritt 1 (gegeben): 1200 m entsprechen 1500 Schritten.\nSchritt 2 (auf 1 m): 1 m entspricht 1500 : 1200 = 1,25 Schritten.\nSchritt 3 (auf 2000 m): 2000 m entsprechen 1,25 · 2000 = 2500 Schritten.\nErgebnis: Auf 2000 m macht sie 2500 Schritte.",
   "quelle": "Dreisatz direkt: Schulweg → Schritte",
   "niveau": "mittel"
  },
  {
   "id": "PR-024",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "offen",
   "frage": "Zeichne den Graphen einer direkt proportionalen Zuordnung in ein Koordinatensystem (Beschreibung genuegt) und erklaere, woran man am Graphen erkennt, dass eine Zuordnung direkt proportional ist.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Der Graph einer direkt proportionalen Zuordnung ist eine Halbgerade (gerade Linie), die im Ursprung (0 | 0) beginnt und gleichmaessig nach oben rechts ansteigt. Beispiel mit k = 2: die Punkte (0|0), (1|2), (2|4), (3|6) liegen alle auf einer Geraden durch den Ursprung.\nMan erkennt direkte Proportionalitaet daran, dass\n1. der Graph durch den Ursprung verlaeuft (zu x = 0 gehoert y = 0) und\n2. der Graph eine gerade Linie (Halbgerade) ist, also gleichmaessig steigt.\nFehlt eine dieser Eigenschaften (z. B. die Linie geht nicht durch den Ursprung oder ist gebogen), ist die Zuordnung nicht direkt proportional.",
   "quelle": "Graph einer direkt proportionalen Zuordnung: Halbgerade durch den Ursprung",
   "niveau": "mittel"
  },
  {
   "id": "PR-025",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler in eigenen Worten: Was bedeutet es, dass zwei Groessen DIREKT proportional zueinander sind? Nenne dazu ein Beispiel aus dem Unterricht.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Direkt proportional bedeutet, wenn die eine Groesse groesser (oder kleiner) wird, wird die andere im GLEICHEN Verhaeltnis groesser (oder kleiner). Wenn man die eine verdoppelt, verdoppelt sich auch die andere; verdreifacht man sie, verdreifacht sich auch die andere. Man sagt auch: \"je mehr, desto mehr\". Der Quotient \\frac{y}{x} ist immer gleich (konstant). Beispiel: Kinotickets und Preis - 2 Tickets kosten doppelt so viel wie 1 Ticket. Oder: Benzinmenge und Gesamtkosten, Arbeitszeit und Lohn, Laenge des Schulwegs und Anzahl der Schritte.",
   "quelle": "GEPRUEFTE INHALTE: direkt vs. indirekt proportional erkennen",
   "niveau": "leicht"
  },
  {
   "id": "PR-026",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler in eigenen Worten: Was bedeutet es, dass zwei Groessen INDIREKT (umgekehrt) proportional zueinander sind? Nenne dazu ein Beispiel aus dem Unterricht.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Indirekt proportional bedeutet, wenn die eine Groesse groesser wird, wird die andere im gleichen Verhaeltnis KLEINER. Verdoppelt man die eine, halbiert sich die andere; verdreifacht man sie, wird die andere ein Drittel. Man sagt auch: \"je mehr, desto weniger\". Das Produkt x \\cdot y ist immer gleich (konstant). Beispiel: Anzahl der Maschinen und Arbeitsdauer - mit doppelt so vielen Maschinen ist man in der halben Zeit fertig. Oder: Groesse der Fliesen und Anzahl der benoetigten Fliesen - je groesser die Fliesen, desto weniger braucht man fuer den Boden.",
   "quelle": "GEPRUEFTE INHALTE: direkt vs. indirekt proportional erkennen",
   "niveau": "leicht"
  },
  {
   "id": "PR-027",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Dein Mitschueler fragt: \"Woran erkenne ich denn, ob etwas DIREKT oder INDIREKT proportional ist?\" Erklaere ihm den Unterschied so, dass er es sich gut merken kann.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Bei DIREKT proportional gilt \"je mehr, desto mehr\" - beide Groessen wachsen zusammen; der Quotient \\frac{y}{x} bleibt gleich. Bei INDIREKT proportional gilt \"je mehr, desto weniger\" - wird die eine groesser, wird die andere kleiner; das Produkt x \\cdot y bleibt gleich. Merkhilfe: Bei direkt bleibt der Quotient konstant (man teilt y durch x), bei indirekt bleibt das Produkt konstant (man multipliziert x mal y). Man kann auch ueberlegen: \"Wenn ich von der einen Groesse doppelt so viel habe - wird die andere dann auch doppelt so gross (direkt) oder nur halb so gross (indirekt)?\"",
   "quelle": "GEPRUEFTE INHALTE: direkt vs. indirekt proportional erkennen",
   "niveau": "mittel"
  },
  {
   "id": "PR-028",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, warum die Zuordnung \"Laenge eines Kinofilms → Anzahl der Zuschauer\" WEDER direkt NOCH indirekt proportional ist.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Die Laenge eines Films hat nichts damit zu tun, wie viele Leute ihn anschauen. Ein langer Film kann viele oder wenige Zuschauer haben, genauso ein kurzer Film. Es gibt keine feste Regel: Wenn der Film doppelt so lang ist, kommen nicht automatisch doppelt so viele (das waere direkt) und auch nicht halb so viele Zuschauer (das waere indirekt). Weder der Quotient noch das Produkt bleibt gleich. Deshalb ist es keine proportionale Zuordnung - die beiden Groessen haengen gar nicht regelmaessig voneinander ab.",
   "quelle": "GEPRUEFTE INHALTE: Laenge eines Kinofilms→Anzahl Zuschauer (nicht proportional)",
   "niveau": "mittel"
  },
  {
   "id": "PR-029",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, wie er bei einer DIREKT proportionalen Wertetabelle herausfindet, ob sie stimmt, und wie er fehlende Werte ergaenzt. Nutze dazu die Tabelle: x: 1; 2,5; 5; 10; 50  und  y: 4; 10; 20; 40; 200.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Bei direkt proportional muss der Quotient \\frac{y}{x} bei jedem Wertepaar gleich sein - das ist der Proportionalitaetsfaktor k. Hier: \\frac{4}{1}=4, \\frac{10}{2,5}=4, \\frac{20}{5}=4, \\frac{40}{10}=4, \\frac{200}{50}=4. Da ueberall 4 herauskommt, ist k=4 und die Tabelle ist direkt proportional. Fehlende y-Werte berechnet man mit y = k \\cdot x (also x mal 4), fehlende x-Werte mit x = \\frac{y}{k} (also y geteilt durch 4). Beispiel: Zu x=5 gehoert y = 4 \\cdot 5 = 20.",
   "quelle": "GEPRUEFTE INHALTE: Wertetabellen ergaenzen, direkt proportional k=4",
   "niveau": "mittel"
  },
  {
   "id": "PR-030",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, wie er bei einer INDIREKT proportionalen Wertetabelle vorgeht. Nutze dazu die Tabelle: x: 2; 4; 10; 12; 20  und  y: 30; 15; 6; 5; 3.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Bei indirekt proportional muss das PRODUKT x \\cdot y bei jedem Wertepaar gleich sein. Hier: 2 \\cdot 30 = 60, 4 \\cdot 15 = 60, 10 \\cdot 6 = 60, 12 \\cdot 5 = 60, 20 \\cdot 3 = 60. Ueberall kommt 60 heraus, also ist k=60 und die Tabelle ist indirekt proportional. Fehlende Werte findet man, indem man k=60 durch den bekannten Wert teilt: fehlendes y = \\frac{60}{x}, fehlendes x = \\frac{60}{y}. Beispiel: Zu x=10 gehoert y = \\frac{60}{10} = 6. Wichtig: Bei indirekt pruefst du mit dem PRODUKT (x mal y muss konstant sein), bei direkt dagegen mit dem Quotienten (y geteilt durch x).",
   "quelle": "GEPRUEFTE INHALTE: Wertetabellen ergaenzen, indirekt proportional k=60",
   "niveau": "mittel"
  },
  {
   "id": "PR-031",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Ein Mitschueler weiss: 9 Eintrittskarten kosten 81 €. Erklaere ihm Schritt fuer Schritt, wie man mit dem Dreisatz den Preis fuer 11 Karten ausrechnet.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Karten und Preis sind direkt proportional (mehr Karten = mehr Geld). Beim Dreisatz geht man ueber den Wert fuer EINE Karte. Schritt 1: 9 Karten kosten 81 €. Schritt 2 (auf 1 herunterrechnen): 1 Karte kostet 81 € : 9 = 9 €. Schritt 3 (auf 11 hochrechnen): 11 Karten kosten 9 € \\cdot 11 = 99 €. Antwort: 11 Karten kosten 99 €. Wichtig zu erklaeren: Weil es direkt proportional ist, teilt man im ersten Schritt und multipliziert im zweiten.",
   "quelle": "GEPRUEFTE INHALTE: Dreisatz-Sachaufgaben, 9 Karten 81€ → 11 Karten 99€",
   "niveau": "mittel"
  },
  {
   "id": "PR-032",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Ein Mitschueler hat folgende Aufgabe: \"2 Pumpen leeren ein Becken in 4 Stunden. Wie lange brauchen 5 Pumpen?\" Er rechnet einfach hoch und kommt auf 10 Stunden. Erklaere ihm, warum das falsch ist und wie man richtig rechnet.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Hier ist es INDIREKT proportional - mehr Pumpen bedeuten WENIGER Zeit (\"je mehr, desto weniger\"). Deshalb darf man nicht einfach hochrechnen wie bei direkt. Richtiger Dreisatz ueber EINE Pumpe: 2 Pumpen brauchen 4 h. 1 Pumpe braucht LAENGER, naemlich 4 h \\cdot 2 = 8 h (mal nehmen statt teilen, weil indirekt). 5 Pumpen brauchen dann 8 h : 5 = 1,6 h. Antwort: 5 Pumpen brauchen 1,6 Stunden. Der Mitschueler hat den Fehler gemacht, die Aufgabe wie eine direkt proportionale zu behandeln - bei indirekt vertauscht man Mal und Geteilt.",
   "quelle": "GEPRUEFTE INHALTE: Dreisatz-Sachaufgaben, 2 Pumpen 4h → 5 Pumpen 1,6h (indirekt)",
   "niveau": "schwer"
  },
  {
   "id": "PR-033",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler, wie man den Proportionalitaetsfaktor k aus einem einzelnen Wertepaar berechnet. Zeige es am Wertepaar (6 | 9) einer direkt proportionalen Zuordnung.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Der Proportionalitaetsfaktor k sagt, mit welcher Zahl man den x-Wert multiplizieren muss, um den y-Wert zu bekommen. Man berechnet ihn bei direkt proportional, indem man y durch x teilt: k = \\frac{y}{x}. Beim Wertepaar (6 | 9) ist x=6 und y=9, also k = 9 : 6 = 1,5. Das bedeutet: Jeder x-Wert wird mit 1,5 multipliziert, um den y-Wert zu erhalten. Probe: 6 \\cdot 1,5 = 9 - stimmt. Mit k kann man dann jeden weiteren Wert ausrechnen.",
   "quelle": "GEPRUEFTE INHALTE: Proportionalitaetsfaktor aus einem Wertepaar, (6|9) → k=1,5",
   "niveau": "mittel"
  },
  {
   "id": "PR-034",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Dein Mitschueler soll im Koordinatensystem erkennen, ob ein Graph zu einer DIREKT proportionalen Zuordnung gehoert. Erklaere ihm, woran man das sieht.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Der Graph einer direkt proportionalen Zuordnung ist immer eine GERADE LINIE (Halbgerade), die durch den URSPRUNG (den Nullpunkt, wo beide Achsen sich treffen) geht. Das ist logisch: Zu 0 (z.B. 0 Liter Benzin) gehoeren 0 (z.B. 0 €) - der Graph startet also im Punkt (0|0). Ausserdem ist die Linie gerade, weil bei jedem Schritt nach rechts die Linie immer gleich viel steigt. Wenn ein Graph gebogen ist oder NICHT durch den Ursprung geht, ist die Zuordnung nicht direkt proportional.",
   "quelle": "GEPRUEFTE INHALTE: Graph einer direkt proportionalen Zuordnung, Halbgerade durch den Ursprung",
   "niveau": "mittel"
  },
  {
   "id": "PR-035",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Ein Broetchen kostet 0,24 €. Erklaere einem Mitschueler, warum die Zuordnung \"Anzahl der Broetchen → Preis\" direkt proportional ist und wie man damit den Preis fuer 5 Broetchen berechnet.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Die Zuordnung ist direkt proportional, weil jedes weitere Broetchen genau 0,24 € mehr kostet - doppelt so viele Broetchen kosten doppelt so viel. Der Preis pro Broetchen (0,24 €) ist der Proportionalitaetsfaktor k und bleibt immer gleich. Den Preis fuer 5 Broetchen rechnet man so: 5 \\cdot 0,24 € = 1,20 €. Allgemein gilt: Preis = Anzahl \\cdot 0,24 €. Man koennte auch eine Wertetabelle machen: 1 Stueck → 0,24 €, 2 Stueck → 0,48 €, 5 Stueck → 1,20 €.",
   "quelle": "GEPRUEFTE INHALTE: Wertetabellen, Broetchen 1 Stueck 0,24 €",
   "niveau": "leicht"
  },
  {
   "id": "PR-036",
   "block": "proportionalitaet",
   "phase": "Mitte",
   "punkte": 20,
   "typ": "erklaeren",
   "frage": "Erklaere einem Mitschueler die Tomaten-Aufgabe: \"5 kg Tomaten kosten 13 €.\" Wie findet man heraus, was 1 kg und was 2,5 kg kosten?",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Kernpunkte einer guten Erklaerung: Gewicht und Preis sind direkt proportional (mehr Tomaten = mehr Geld). Man rechnet zuerst auf 1 kg herunter (Dreisatz): 5 kg kosten 13 €, also kostet 1 kg = 13 € : 5 = 2,60 €. Das ist der Preis pro Kilo (Proportionalitaetsfaktor). Fuer 2,5 kg multipliziert man wieder hoch: 2,5 \\cdot 2,60 € = 6,50 €. Antwort: 1 kg kostet 2,60 €, 2,5 kg kosten 6,50 €. Wichtiger Trick: Erst durch die gegebene Menge teilen (Preis fuer 1 kg), dann mit der gesuchten Menge multiplizieren.",
   "quelle": "GEPRUEFTE INHALTE: Dreisatz-Sachaufgaben, Tomaten 5 kg 13 € → 1 kg / 2,5 kg",
   "niveau": "mittel"
  },
  {
   "id": "WI-001",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "Ein Winkel hat die Groesse α = 35°. Welche Winkelart ist das?",
   "optionen": [
    "spitzer Winkel",
    "rechter Winkel",
    "stumpfer Winkel",
    "gestreckter Winkel"
   ],
   "loesungIndex": 0,
   "loesung": "Ein Winkel zwischen 0° und 90° heisst spitzer Winkel. Da 35° kleiner als 90° ist, ist α ein spitzer Winkel.",
   "quelle": "Winkelarten benennen",
   "niveau": "leicht"
  },
  {
   "id": "WI-002",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "Welche Aussage ueber die Groesse eines stumpfen Winkels ist richtig?",
   "optionen": [
    "genau 90°",
    "zwischen 0° und 90°",
    "zwischen 90° und 180°",
    "genau 180°"
   ],
   "loesungIndex": 2,
   "loesung": "Ein stumpfer Winkel ist groesser als 90° und kleiner als 180°, liegt also zwischen 90° und 180°. 90° ist ein rechter, 180° ein gestreckter Winkel.",
   "quelle": "Winkelarten benennen",
   "niveau": "leicht"
  },
  {
   "id": "WI-003",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "Wie nennt man einen Winkel, der genau 180° gross ist?",
   "optionen": [
    "rechter Winkel",
    "stumpfer Winkel",
    "gestreckter Winkel",
    "ueberstumpfer Winkel"
   ],
   "loesungIndex": 2,
   "loesung": "Ein Winkel von genau 180° heisst gestreckter Winkel (die beiden Schenkel bilden eine Gerade). Ueberstumpfe Winkel liegen zwischen 180° und 360°.",
   "quelle": "Winkelarten benennen",
   "niveau": "leicht"
  },
  {
   "id": "WI-004",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "Zwei Geraden g und h sind parallel und werden von einer dritten Geraden geschnitten. Ein Stufenwinkel betraegt 70°. Wie gross ist der zugehoerige Stufenwinkel an der anderen Parallelen?",
   "optionen": [
    "20°",
    "70°",
    "110°",
    "180°"
   ],
   "loesungIndex": 1,
   "loesung": "An geschnittenen Parallelen sind Stufenwinkel gleich gross. Der zugehoerige Stufenwinkel betraegt also ebenfalls 70°.",
   "quelle": "Winkel an geschnittenen Parallelen",
   "niveau": "leicht"
  },
  {
   "id": "WI-005",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "An zwei geschnittenen Parallelen betraegt ein Winkel 110°. Wie gross ist sein Nebenwinkel?",
   "optionen": [
    "110°",
    "90°",
    "70°",
    "55°"
   ],
   "loesungIndex": 2,
   "loesung": "Nebenwinkel ergaenzen sich zu 180°. Es gilt 180° − 110° = 70°. Der Nebenwinkel betraegt also 70°.",
   "quelle": "Winkel an geschnittenen Parallelen (Nebenwinkel)",
   "niveau": "mittel"
  },
  {
   "id": "WI-006",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "In einem Dreieck sind zwei Winkel gegeben: 45° und 62°. Wie gross ist der dritte Winkel?",
   "optionen": [
    "73°",
    "83°",
    "107°",
    "63°"
   ],
   "loesungIndex": 0,
   "loesung": "Die Winkelsumme im Dreieck ist 180°. Es gilt 180° − 45° − 62° = 73°. Der dritte Winkel betraegt 73°.",
   "quelle": "Winkelsumme im Dreieck",
   "niveau": "mittel"
  },
  {
   "id": "WI-007",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "Ein Dreieck hat die Winkel 37°, 42° und 101°. Welche Dreiecksart ist das (nach den Winkeln)?",
   "optionen": [
    "spitzwinklig",
    "rechtwinklig",
    "stumpfwinklig",
    "gleichseitig"
   ],
   "loesungIndex": 2,
   "loesung": "Ein Winkel (101°) ist groesser als 90°, also stumpf. Ein Dreieck mit einem stumpfen Winkel heisst stumpfwinklig.",
   "quelle": "Dreiecksart nach Winkeln",
   "niveau": "mittel"
  },
  {
   "id": "WI-008",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "Ein Dreieck hat die Winkel 45° und 45°. Welche Art von Dreieck ist es?",
   "optionen": [
    "spitzwinklig",
    "rechtwinklig",
    "stumpfwinklig",
    "gestreckt"
   ],
   "loesungIndex": 1,
   "loesung": "Der dritte Winkel ist 180° − 45° − 45° = 90°. Da ein Winkel genau 90° betraegt, ist das Dreieck rechtwinklig.",
   "quelle": "Winkelsumme und Dreiecksart",
   "niveau": "mittel"
  },
  {
   "id": "WI-009",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "Kann man aus den drei Seiten a = 3 cm, b = 4 cm und c = 8 cm ein Dreieck konstruieren?",
   "optionen": [
    "Ja, denn alle Seiten sind verschieden lang.",
    "Nein, denn 3 + 4 = 7 ist kleiner als 8.",
    "Ja, denn 8 ist die laengste Seite.",
    "Nein, denn die Seiten sind zu kurz."
   ],
   "loesungIndex": 1,
   "loesung": "Nach der Dreiecksungleichung muss die Summe zweier Seiten groesser als die dritte sein. Hier ist 3 + 4 = 7 < 8, also ist das Dreieck NICHT konstruierbar.",
   "quelle": "Dreiecksungleichung",
   "niveau": "schwer"
  },
  {
   "id": "WI-010",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "Ein Dreieck soll mit c = 7 cm, α = 110° und β = 80° konstruiert werden. Ist das moeglich?",
   "optionen": [
    "Ja, denn beide Winkel sind stumpf bzw. fast stumpf.",
    "Ja, denn die Seite c ist lang genug.",
    "Nein, denn 110° + 80° = 190° ist groesser als 180°.",
    "Nein, denn man braucht immer drei Winkel."
   ],
   "loesungIndex": 2,
   "loesung": "Die Winkelsumme im Dreieck ist 180°. Hier ergeben α + β = 110° + 80° = 190° > 180°, somit bliebe fuer γ kein Platz. Das Dreieck ist NICHT konstruierbar.",
   "quelle": "Konstruierbarkeit (Winkelsumme)",
   "niveau": "schwer"
  },
  {
   "id": "WI-011",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "Wie konstruiert man die Mittelsenkrechte einer 5 cm langen Strecke AB?",
   "optionen": [
    "Man zeichnet einen einzigen Kreis um den Mittelpunkt der Strecke.",
    "Man schlaegt zwei gleich grosse Kreisboegen um A und um B und verbindet die Schnittpunkte.",
    "Man misst 2,5 cm ab und zeichnet dort einen Punkt.",
    "Man verbindet A und B mit einer schraegen Geraden."
   ],
   "loesungIndex": 1,
   "loesung": "Fuer die Mittelsenkrechte schlaegt man um die beiden Endpunkte A und B jeweils gleich grosse Kreisboegen (Radius groesser als die halbe Strecke). Die Gerade durch die beiden Schnittpunkte ist die Mittelsenkrechte.",
   "quelle": "Konstruktion Mittelsenkrechte",
   "niveau": "mittel"
  },
  {
   "id": "WI-012",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "mc",
   "frage": "In einem Dreieck ist α sechsmal so gross wie β, und β ist doppelt so gross wie γ. Wie gross sind die drei Winkel?",
   "optionen": [
    "γ = 12°, β = 24°, α = 144°",
    "γ = 20°, β = 40°, α = 120°",
    "γ = 10°, β = 20°, α = 150°",
    "γ = 15°, β = 30°, α = 135°"
   ],
   "loesungIndex": 0,
   "loesung": "Setze γ = x, dann β = 2x und α = 6 \\cdot (2x) = 12x. Die Summe ist x + 2x + 12x = 15x = 180°, also x = 12°. Damit gilt γ = 12°, β = 24° und α = 144°.",
   "quelle": "Knobelaufgabe Winkelverhaeltnisse",
   "niveau": "schwer"
  },
  {
   "id": "WI-013",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Benenne die folgenden Winkel nach ihrer Art (spitz, recht, stumpf, gestreckt oder ueberstumpf): α = 35°, β = 90°, γ = 128°, δ = 180°, ε = 250°.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "α = 35° liegt zwischen 0° und 90° → spitzer Winkel. β = 90° → rechter Winkel. γ = 128° liegt zwischen 90° und 180° → stumpfer Winkel. δ = 180° → gestreckter Winkel. ε = 250° liegt zwischen 180° und 360° → ueberstumpfer Winkel.",
   "quelle": "Winkelarten benennen",
   "niveau": "leicht"
  },
  {
   "id": "WI-014",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "In einem Dreieck sind zwei Winkel gegeben: α = 64° und β = 58°. Berechne den dritten Winkel γ und gib an, um welche Dreiecksart (nach den Winkeln) es sich handelt.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Die Winkelsumme im Dreieck betraegt 180°. Also: γ = 180° − 64° − 58° = 58°. Alle drei Winkel (64°, 58°, 58°) sind kleiner als 90°, daher ist das Dreieck spitzwinklig. Ergebnis: γ = 58°, spitzwinkliges Dreieck.",
   "quelle": "Winkelsumme im Dreieck",
   "niveau": "leicht"
  },
  {
   "id": "WI-015",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Ein Dreieck hat die Winkel α = 53° und γ = 90°. Berechne den fehlenden Winkel β und nenne die Dreiecksart.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Winkelsumme = 180°. β = 180° − 53° − 90° = 37°. Da ein Winkel genau 90° gross ist, handelt es sich um ein rechtwinkliges Dreieck. Ergebnis: β = 37°, rechtwinkliges Dreieck.",
   "quelle": "Winkelsumme im Dreieck",
   "niveau": "leicht"
  },
  {
   "id": "WI-016",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Zwei Parallelen g und h werden von einer Geraden geschnitten. An g entsteht ein Winkel von 72°. Bestimme ohne zu messen den Wechselwinkel dazu an h und den Nebenwinkel des Wechselwinkels. Begruende kurz.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Wechselwinkel an geschnittenen Parallelen sind gleich gross. Der Wechselwinkel an h betraegt also 72°. Der Nebenwinkel ergaenzt sich mit dem Wechselwinkel zu 180°: 180° − 72° = 108°. Ergebnis: Wechselwinkel = 72°, Nebenwinkel = 108°.",
   "quelle": "Winkel an Parallelen",
   "niveau": "mittel"
  },
  {
   "id": "WI-017",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Zu einem Winkel von 117° soll der Nebenwinkel bestimmt werden. Berechne den Nebenwinkel und gib an, ob er spitz oder stumpf ist.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Nebenwinkel ergaenzen sich zu 180°. Nebenwinkel = 180° − 117° = 63°. Da 63° zwischen 0° und 90° liegt, ist es ein spitzer Winkel. Ergebnis: Nebenwinkel = 63°, spitz.",
   "quelle": "Nebenwinkel",
   "niveau": "leicht"
  },
  {
   "id": "WI-018",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Pruefe, ob ein Dreieck mit den Seiten a = 3 cm, b = 4 cm und c = 8 cm konstruiert werden kann. Begruende deine Antwort mit der passenden Regel.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Es gilt die Dreiecksungleichung: Die Summe zweier Seiten muss groesser als die dritte Seite sein. Pruefung der beiden kuerzeren Seiten gegen die laengste: a + b = 3 cm + 4 cm = 7 cm. Das ist kleiner als c = 8 cm (7 cm < 8 cm). Damit ist die Dreiecksungleichung verletzt. Ergebnis: Das Dreieck ist NICHT konstruierbar.",
   "quelle": "Dreiecksungleichung",
   "niveau": "mittel"
  },
  {
   "id": "WI-019",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Kann ein Dreieck mit c = 7 cm, α = 110° und β = 80° konstruiert werden? Begruende.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Die Winkelsumme im Dreieck muss genau 180° betragen, die beiden gegebenen Winkel duerfen zusammen also kleiner als 180° sein. Hier gilt: α + β = 110° + 80° = 190°. Das ist groesser als 180° (190° > 180°). Damit bliebe fuer den dritten Winkel kein Platz mehr. Ergebnis: Das Dreieck ist NICHT konstruierbar.",
   "quelle": "Winkelsumme als Konstruierbarkeitsbedingung",
   "niveau": "mittel"
  },
  {
   "id": "WI-020",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Beschreibe in der richtigen Reihenfolge die Konstruktionsschritte fuer die Mittelsenkrechte einer 5 cm langen Strecke AB.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "1. Zeichne die Strecke AB mit der Laenge 5 cm. 2. Stich den Zirkel in A ein und schlage einen Kreisbogen mit einem Radius, der groesser als die Haelfte von AB (also groesser als 2,5 cm) ist. 3. Stich den Zirkel in B ein und schlage mit dem GLEICHEN Radius einen zweiten Kreisbogen. 4. Die beiden Kreisboegen schneiden sich in zwei Punkten (oberhalb und unterhalb der Strecke). 5. Verbinde diese beiden Schnittpunkte mit einer Geraden. Diese Gerade ist die Mittelsenkrechte; sie steht senkrecht auf AB und halbiert die Strecke im Mittelpunkt.",
   "quelle": "Konstruktion Mittelsenkrechte",
   "niveau": "mittel"
  },
  {
   "id": "WI-021",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Beschreibe Schritt fuer Schritt, wie man ein gleichseitiges Dreieck mit der Seitenlaenge 3 cm konstruiert (nur mit Zirkel und Lineal).",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "1. Zeichne eine Strecke AB mit der Laenge 3 cm. 2. Stich den Zirkel in A ein, stelle den Radius auf 3 cm und schlage einen Kreisbogen oberhalb der Strecke. 3. Stich den Zirkel in B ein, behalte den Radius 3 cm bei und schlage einen zweiten Kreisbogen, der den ersten schneidet. 4. Der Schnittpunkt der beiden Boegen ist der Punkt C. 5. Verbinde C mit A und C mit B. Es entsteht das gleichseitige Dreieck ABC mit drei gleich langen Seiten von je 3 cm (und drei 60°-Winkeln).",
   "quelle": "Konstruktion gleichseitiges Dreieck",
   "niveau": "mittel"
  },
  {
   "id": "WI-022",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Bringe die folgenden Konstruktionsschritte fuer ein Dreieck nach SWS (Seite-Winkel-Seite) mit c = 6 cm, α = 50° und b = 4 cm in die richtige Reihenfolge: (A) Verbinde C mit B. (B) Trage an A den Winkel α = 50° an. (C) Zeichne die Strecke AB = c = 6 cm. (D) Trage auf dem freien Schenkel von A die Laenge b = 4 cm ab und markiere den Punkt C.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Richtige Reihenfolge: C – B – D – A. Begruendung: Zuerst zeichnet man die gegebene Seite AB = c = 6 cm (Schritt C). Dann traegt man im Punkt A den gegebenen Winkel α = 50° an (Schritt B). Anschliessend markiert man auf dem neuen Schenkel die Laenge b = 4 cm und erhaelt den Punkt C (Schritt D). Zuletzt verbindet man C mit B, um das Dreieck zu schliessen (Schritt A). Ergebnis: C, B, D, A.",
   "quelle": "Konstruktion SWS, Reihenfolge",
   "niveau": "schwer"
  },
  {
   "id": "WI-023",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Ein Dreieck hat die Winkel 37° und 42°. Berechne den dritten Winkel und gib die Dreiecksart nach den Winkeln an.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Winkelsumme = 180°. Dritter Winkel = 180° − 37° − 42° = 101°. Da ein Winkel groesser als 90° ist (101° liegt zwischen 90° und 180°), handelt es sich um ein stumpfwinkliges Dreieck. Ergebnis: dritter Winkel = 101°, stumpfwinkliges Dreieck.",
   "quelle": "Winkelsumme und Dreiecksart",
   "niveau": "leicht"
  },
  {
   "id": "WI-024",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "offen",
   "frage": "Knobelaufgabe: In einem Dreieck ist der Winkel α sechsmal so gross wie β, und β ist doppelt so gross wie γ. Berechne alle drei Winkel.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Wir druecken alles durch γ aus. β = 2 · γ. Da α sechsmal so gross wie β ist: α = 6 · β = 6 · (2 · γ) = 12 · γ. Die Winkelsumme betraegt 180°: α + β + γ = 12γ + 2γ + γ = 15γ = 180°. Also γ = \\frac{180°}{15} = 12°. Daraus folgt: β = 2 · 12° = 24° und α = 12 · 12° = 144°. Probe: 144° + 24° + 12° = 180°. Ergebnis: γ = 12°, β = 24°, α = 144°.",
   "quelle": "Knobelaufgabe Winkelsumme",
   "niveau": "schwer"
  },
  {
   "id": "WI-025",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Erkläre einem Mitschüler, wie man die fünf Winkelarten erkennt. Nenne zu jeder Art den Bereich der Gradzahl und ein Beispiel.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung nennt alle fünf Arten mit ihren Grenzen: Spitzer Winkel: größer als 0° und kleiner als 90° (z. B. α = 35°). Rechter Winkel: genau 90° (oft mit kleinem Kästchen markiert). Stumpfer Winkel: größer als 90° und kleiner als 180° (z. B. 120°). Gestreckter Winkel: genau 180° (sieht aus wie eine gerade Linie). Überstumpfer Winkel: größer als 180° und kleiner als 360° (z. B. 270°). Wichtig: Man schaut also einfach, in welchen Bereich die Gradzahl fällt, und kann den Namen sofort bestimmen.",
   "quelle": "Winkel & Dreiecke - Winkelarten benennen",
   "niveau": "leicht"
  },
  {
   "id": "WI-026",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Ein Mitschüler hat keinen Geodreieck-Profi-Trick parat. Erkläre ihm Schritt für Schritt, wie man mit dem Geodreieck einen Winkel von 50° zeichnet.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung enthält diese Schritte: 1) Zuerst einen Punkt (Scheitelpunkt) markieren und von dort einen Schenkel (eine gerade Linie) zeichnen. 2) Den Mittelpunkt des Geodreiecks (das kleine Loch / die Markierung in der Mitte der langen Kante) genau auf den Scheitelpunkt legen. 3) Die lange Kante (Nulllinie) genau auf den schon gezeichneten Schenkel legen. 4) Auf der richtigen Gradskala (von 0° hochzählen) die 50° suchen und dort einen Punkt setzen. 5) Geodreieck wegnehmen und den zweiten Schenkel vom Scheitelpunkt durch den 50°-Punkt ziehen. Tipp: Darauf achten, die richtige der beiden Skalen zu benutzen (immer von der 0 aus zählen, die auf dem schon gezeichneten Schenkel liegt).",
   "quelle": "Winkel & Dreiecke - Winkel zeichnen und messen",
   "niveau": "mittel"
  },
  {
   "id": "WI-027",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Zwei Geraden g und h sind parallel und werden von einer dritten Geraden geschnitten. Erkläre einem Mitschüler, was Stufenwinkel und Wechselwinkel sind und welche besondere Eigenschaft sie an parallelen Geraden haben.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung sagt: An jedem der beiden Schnittpunkte entstehen vier Winkel. Stufenwinkel liegen an verschiedenen Schnittpunkten auf der gleichen Seite der schneidenden Geraden und zeigen in dieselbe Richtung (wie zwei Stufen einer Treppe). Wechselwinkel liegen auf entgegengesetzten Seiten der schneidenden Geraden, also über Kreuz (sie 'wechseln' die Seite). Die besondere Eigenschaft bei parallelen Geraden: Stufenwinkel sind gleich groß und Wechselwinkel sind gleich groß. Deshalb kann man fehlende Winkel bestimmen, ohne sie zu messen: Man überträgt einfach die gleiche Gradzahl.",
   "quelle": "Winkel & Dreiecke - Winkel an geschnittenen Parallelen",
   "niveau": "mittel"
  },
  {
   "id": "WI-028",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "An zwei geschnittenen Parallelen ist ein Winkel mit 70° bekannt. Erkläre einem Mitschüler, wie er den Nebenwinkel bestimmt, ohne zu messen, und warum das funktioniert.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung sagt: Nebenwinkel sind zwei Winkel, die zusammen einen gestreckten Winkel (180°) bilden, weil sie an einer geraden Linie nebeneinanderliegen. Sie ergänzen sich also immer zu 180°. Rechnung: 180° − 70° = 110°. Der Nebenwinkel ist 110°. Man muss nichts messen, weil eine gerade Linie immer 180° hat und der bekannte Winkel davon 70° wegnimmt; der Rest ist der Nebenwinkel.",
   "quelle": "Winkel & Dreiecke - Nebenwinkel an Parallelen",
   "niveau": "leicht"
  },
  {
   "id": "WI-029",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Erkläre einem Mitschüler den Satz über die Winkelsumme im Dreieck und zeige an dem Beispiel (45°, ?, 62°), wie man den fehlenden Winkel berechnet.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung sagt: In jedem Dreieck ergeben die drei Innenwinkel zusammen immer 180°. Das gilt für jedes Dreieck, egal wie es aussieht. Um einen fehlenden Winkel zu finden, addiert man die beiden bekannten Winkel und zieht die Summe von 180° ab. Rechnung: 45° + 62° = 107°. Dann 180° − 107° = 73°. Der fehlende Winkel ist also 73°.",
   "quelle": "Winkel & Dreiecke - Winkelsumme im Dreieck",
   "niveau": "leicht"
  },
  {
   "id": "WI-030",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Erkläre einem Mitschüler, wie man ein Dreieck nach seinen Winkeln einteilt (spitzwinklig, rechtwinklig, stumpfwinklig). Bestimme dazu die Art des Dreiecks mit den Winkeln 37°, 42° und dem fehlenden dritten Winkel.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung sagt: Man schaut auf den größten Winkel des Dreiecks. Sind alle drei Winkel kleiner als 90°, ist das Dreieck spitzwinklig. Ist ein Winkel genau 90°, ist es rechtwinklig. Ist ein Winkel größer als 90°, ist es stumpfwinklig. Zuerst den fehlenden Winkel berechnen: 37° + 42° = 79°, dann 180° − 79° = 101°. Der größte Winkel ist 101°, also größer als 90°. Das Dreieck ist deshalb stumpfwinklig.",
   "quelle": "Winkel & Dreiecke - Dreiecksart nach Winkeln",
   "niveau": "mittel"
  },
  {
   "id": "WI-031",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Erkläre einem Mitschüler die Dreiecksungleichung. Begründe damit, warum man aus den Seiten a = 3 cm, b = 4 cm und c = 8 cm KEIN Dreieck zeichnen kann.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung sagt: Die Dreiecksungleichung besagt, dass die Summe von zwei Seiten immer größer sein muss als die dritte Seite. Anschaulich: Zwei kürzere Seiten müssen zusammen 'lang genug' sein, um sich über der längsten Seite zu treffen. Prüfung beim Beispiel: a + b = 3 + 4 = 7 cm, aber die dritte Seite c ist 8 cm. Da 7 cm < 8 cm, sind die beiden kurzen Seiten zusammen kürzer als die lange Seite; sie können sich nicht treffen. Deshalb ist das Dreieck NICHT konstruierbar.",
   "quelle": "Winkel & Dreiecke - Dreiecksungleichung",
   "niveau": "mittel"
  },
  {
   "id": "WI-032",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Ein Mitschüler soll ein Dreieck mit c = 7 cm, α = 110° und β = 80° zeichnen und kommt nicht weiter. Erkläre ihm, warum dieses Dreieck gar nicht möglich ist.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung sagt: In jedem Dreieck müssen die drei Innenwinkel zusammen genau 180° ergeben. Schon zwei der Winkel sind hier α = 110° und β = 80°. Rechnung: 110° + 80° = 190°. Das sind allein für zwei Winkel schon 190°, also mehr als 180°. Für den dritten Winkel γ bliebe gar kein Platz mehr (er müsste sogar negativ sein). Weil die Winkelsumme über 180° liegt, ist das Dreieck NICHT konstruierbar.",
   "quelle": "Winkel & Dreiecke - Konstruierbarkeit Winkelsumme",
   "niveau": "mittel"
  },
  {
   "id": "WI-033",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Erkläre einem Mitschüler in der richtigen Reihenfolge, wie man ein gleichseitiges Dreieck mit der Seitenlänge 3 cm mit Zirkel und Lineal konstruiert.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung nennt die Schritte in dieser Reihenfolge: 1) Eine Strecke AB von genau 3 cm Länge mit dem Lineal zeichnen (das ist die erste Seite). 2) Den Zirkel auf 3 cm einstellen. 3) Zirkelspitze in den Punkt A setzen und einen Kreisbogen zeichnen. 4) Zirkelspitze (immer noch 3 cm) in den Punkt B setzen und einen zweiten Kreisbogen zeichnen. 5) Wo sich die beiden Bögen schneiden, liegt der Punkt C. 6) C mit A und C mit B verbinden. Begründung: Weil alle drei Seiten 3 cm lang sind (durch die gleiche Zirkelöffnung), ist das Dreieck gleichseitig.",
   "quelle": "Winkel & Dreiecke - Konstruktion gleichseitiges Dreieck",
   "niveau": "mittel"
  },
  {
   "id": "WI-034",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Erkläre einem Mitschüler, wie man die Mittelsenkrechte einer 5 cm langen Strecke AB mit dem Zirkel konstruiert und was eine Mittelsenkrechte überhaupt ist.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung sagt: Die Mittelsenkrechte ist die Gerade, die genau durch die Mitte der Strecke geht und dort senkrecht (im rechten Winkel, 90°) auf der Strecke steht. Konstruktion: 1) Den Zirkel auf eine Öffnung einstellen, die größer als die Hälfte der Strecke ist (also größer als 2,5 cm). 2) Zirkelspitze in den Endpunkt A setzen und einen Kreisbogen über und unter der Strecke zeichnen. 3) Mit GLEICHER Zirkelöffnung die Spitze in den Endpunkt B setzen und wieder einen Bogen zeichnen. 4) Die beiden Bögen schneiden sich in zwei Punkten (oben und unten). 5) Diese beiden Schnittpunkte mit dem Lineal verbinden - das ist die Mittelsenkrechte. Wichtig ist die gleiche Zirkelöffnung bei A und B, damit die Linie wirklich genau in der Mitte und senkrecht liegt.",
   "quelle": "Winkel & Dreiecke - Konstruktion Mittelsenkrechte",
   "niveau": "schwer"
  },
  {
   "id": "WI-035",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Erkläre einem Mitschüler, was die Konstruktionsart SWS bedeutet, und beschreibe, wie man damit ein Dreieck mit c = 6 cm, a = 5 cm und dem eingeschlossenen Winkel β = 60° konstruiert.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung sagt: SWS steht für Seite-Winkel-Seite. Man kennt zwei Seiten und den Winkel, der zwischen diesen beiden Seiten liegt (der von ihnen eingeschlossen wird). Hier liegt β zwischen den Seiten c und a. Schritte: 1) Eine der Seiten zeichnen, z. B. Strecke c = 6 cm von A nach B. 2) Im Punkt B den Winkel β = 60° mit dem Geodreieck antragen. 3) Vom Punkt B aus auf dem neuen Schenkel die Seite a = 5 cm abtragen; der Endpunkt ist C. 4) Punkt C mit A verbinden. Fertig ist das Dreieck. Weil zwei Seiten und der eingeschlossene Winkel fest vorgegeben sind, ist das Dreieck eindeutig konstruierbar.",
   "quelle": "Winkel & Dreiecke - Dreieckskonstruktion SWS",
   "niveau": "mittel"
  },
  {
   "id": "WI-036",
   "block": "winkel",
   "phase": "Ende",
   "punkte": 10,
   "typ": "erklaeren",
   "frage": "Knobelaufgabe zum Erklären: In einem Dreieck ist α sechsmal so groß wie β, und β ist doppelt so groß wie γ. Erkläre einem Mitschüler, wie man damit alle drei Winkel herausfindet.",
   "optionen": [],
   "loesungIndex": -1,
   "loesung": "Eine gute Erklärung sagt: Man drückt alle Winkel durch den kleinsten Winkel γ aus. Es gilt β = 2 · γ (β ist doppelt so groß wie γ). Und α = 6 · β = 6 · (2 · γ) = 12 · γ (α ist sechsmal so groß wie β). Nun nutzt man die Winkelsumme 180°: α + β + γ = 180°, also 12·γ + 2·γ + 1·γ = 15·γ = 180°. Daraus γ = 180° : 15 = 12°. Dann β = 2 · 12° = 24° und α = 6 · 24° = 144°. Probe: 144° + 24° + 12° = 180°, passt. Die drei Winkel sind also γ = 12°, β = 24° und α = 144°.",
   "quelle": "Winkel & Dreiecke - Knobelaufgabe Winkelverhältnisse",
   "niveau": "schwer"
  }
 ]
};
